FROM python:3.8.16-slim-bullseye
LABEL MAINTAINER=sc765@duke.edu

# # Install Python
# RUN apt update &&\
#     apt install build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev wget &&\
#     curl -O https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz &&\
#     tar -xzf Python-3.8.12.tgz &&\
#     cd Python-3.8.12 &&\
#     ./configure --enable-optimizations &&\
#     make &&\
#     make install &&\
#     update-alternatives --install /usr/bin/python python /usr/local/bin/python3.8 2

# # Install pip
# RUN apt install curl -y &&\
#     curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py &&\
#     python get-pip.py

# RUN cd .. &&\
#     rm -rf Python-3.8.12 &&\
#     rm Python-3.8.12.tgz

# # install mongodb
RUN apt-get update &&\
    apt-get install -y gnupg &&\
    apt-get install -y wget &&\
    wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add - &&\
    echo "deb http://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list &&\
    apt-get update &&\
    apt-get install -y mongodb-org=6.0.4 mongodb-org-database=6.0.4 mongodb-org-server=6.0.4 mongodb-org-mongos=6.0.4 mongodb-org-tools=6.0.4

# install make
RUN apt-get update &&\
    apt-get install -y make

# #install docker
# RUN apt install apt-transport-https ca-certificates curl gnupg2 software-properties-common -y &&\
#     curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - &&\
#     add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" &&\
#     apt update &&\
#     apt install docker-ce -y

# install dependencies
COPY ./Makefile ./
COPY ./requirements.txt ./
RUN make install &&\
    rm Makefile requirements.txt


EXPOSE 8888 6006
