name: FDS Web App
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: push to azure
      uses: azure/docker-login@v1
      with:
        login-server: fluiddatastream.azurecr.io
        username: ${{ secrets.azure_user_name }}
        password: ${{ secrets.azure_password }}

    - name: Deploy
      run: |
        make deploy