name: FDS Web App
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Package Registry
      run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login registry.hub.docker.com -p -u ${{ secrets.DOCKERHUB_USERNAME }}

    - name: login to azure
      uses: azure/docker-login@v1
      with:
        login-server: fluiddatastream.azurecr.io
        username: ${{ secrets.azure_user_name }}
        password: ${{ secrets.azure_password }}

    - name: Deploy
      run: |
        make deploy